# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 08:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0028_remove_unit_extra_searchwords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='root_ontologytreenodes',
            field=models.TextField(null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
