# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-29 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0062_unit_root_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitidentifier',
            name='value',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='unitidentifier',
            unique_together=set([('namespace', 'value'), ('unit', 'namespace')]),
        ),
    ]
