# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-08 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0063_unit_ptv_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='ext_id',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name='servicenode',
            name='ext_id',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
    ]
