# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-31 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0065_tune_unit_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicenode',
            name='ext_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
